export const examples = [
	['dog', 'cat'],
	['pizza', 'burger'],
	['beach', 'mountain'], //!!!!
	['coffee', 'tea'],
	['car', 'bus'],
	['sun', 'moon'],
	['banana', 'apple'],
	['perfume', 'deodorant'],
	['adidas', 'nike'],
	['backpack', 'suitcase'],
	['jacuzzi', 'sauna'],
	['sneakers', 'sandals'],
	['sunglasses', 'eyeglasses'],
	['piano', 'guitar'],
	['cruise', 'safari'],
	['sushi', 'pizza'],
	['hamburger', 'hotdog'],
	['chocolate', 'vanilla'],
	['beer', 'wine'],
	['whiskey', 'vodka'],
	['milk', 'juice'],
	['bread', 'butter'], //!!!!
	['rice', 'pasta'],
	['chicken', 'beef'],
	['apple', 'orange'],
	['banana', 'strawberry'],
	['carrot', 'broccoli'],
	['potato', 'tomato'],
	['onion', 'garlic'],
	['salt', 'pepper'],
	['sugar', 'honey'],
	['water', 'soda'],
	['apple', 'microsoft'],
	['google', 'facebook'],
	['twitch', 'netflix'],
	['pancake', 'doughnut'],
	['ice cream', 'cake'],
	['mcdonalds', 'kfc'],
	['car', 'bike'],
	['virus', 'bacteria'],
	['lord of the rings', 'hobbit'],
	['harry potter', 'lord voldemort'],
	['superman', 'batman'],
	['spiderman', 'ironman'],
	['captain america', 'thor'],
	['pizza', 'pasta'],
	['football', 'basketball'],
	['music', 'dancing'],
	['dog', 'wolf'],
	['apple', 'pear'],
	['car', 'truck'],
	['pencil', 'pen'],
	['pizza', 'lasagna'],
	['facebook', 'instagram'],
	['sunglasses', 'goggles'],
	['laptop', 'tablet'],
	['doctor', 'surgeon'],
	['bomb', 'gun'],
	['einstein', 'newton'],
	['shirt', 'sweater'],
	['soccer', 'rugby'],
	['plane', 'helicopter'],
	['river', 'lake'],
	['ocean', 'river'],
	['bicycle', 'motorcycle'],
	['salt', 'sugar'],
	['knife', 'scissors'],
	['chair', 'bench'],
	['castle', 'house'],
	['train', 'bus'],
	['mirror', 'window pane'],
	['mouse', 'rat'],
	['cucumber', 'zucchini'], //!!!!
	['strawberry', 'raspberry'],
	['coconut', 'pineapple'],
	['dragon', 'dinosaur'],
	['ghost', 'zombie'],
	['chef', 'kitchen counter'],
	['shovel', 'axe'],
	['pyramid', 'temple'],
	['volcano', 'mountain'],
	['desert', 'sand'],
	['cloud', 'fog'],
	['snow', 'hail'],
	['detective', 'criminal'],
	['jungle', 'forest'],
	['clock', 'watch'],
	['bread', 'toast'],
	['painting', 'sketch'],
	['umbrella', 'parasol'],
	['suit', 'necktie'],
	['socks', 'stockings'],
	['belt', 'jeans'],
	['crown', 'hat'],
	['ballet', 'hip hop'],
	['parrot', 'crow'],
	['bat', 'owl'],
	['candle', 'lantern'],
	['library', 'university'],
	['museum', 'gallery'],
	['radio', 'podcast'],
	['online news', 'newspaper'],
	['pen', 'paper'],
	['moon', 'sun'],
	['tennis', 'badminton'],
	['skiing', 'snow'],
	['swimming', 'diving'],
	['running', 'jogging'],
	['elevator', 'escalator'],
	['ferry', 'cruise'],
	['map', 'gps'],
	['sailboat', 'yacht'],
	['meteor', 'satellite'],
	['planet', 'star'],
	['earthquake', 'tsunami'],
	['jellyfish', 'octopus'],
	['wolf', 'fox'],
	['hawk', 'vulture'],
	['lizard', 'gecko'],
	['elvis', 'the beatles'],
	['leonardo da vinci', 'michelangelo'],
	['napoleon', 'caesar'],
	['mario', 'luigi'],
	['sonic', 'tails'],
	['pac-man', 'tetris'],
	['fortnite', 'minecraft'],
	['call of duty', 'battlefield'],
	['game of thrones', 'lord of the rings'],
	['star wars', 'star trek'],
	['harry potter', 'percy jackson'],
	['sherlock holmes', 'hercule poirot'],
	['dracula', 'frankenstein'],
	['james bond', 'secret service'],
	['homer simpson', 'peter griffin'],
	['spongebob', 'patrick'],
	['godzilla', 'king kong'],
	['lego', 'playmobil'],
	['uno', 'monopoly'],
	['catan', 'risk'],
	['blackjack', 'poker'],
	['bingo', 'roulette'],
	['new york', 'los angeles'],
	['paris', 'london'],
	['rome', 'athens'],
	['sydney', 'melbourne'],
	['rio de janeiro', 'buenos aires'],
	['mount everest', 'nepal'],
	['amazon', 'nile'],
	['grand canyon', 'niagara falls'],
	['taj mahal', 'great wall of china'],
	['eiffel tower', 'statue of liberty'],
	['big ben', 'leaning tower of pisa'],
	['olympics', 'world cup'],
	['nba', 'nfl'],
	['golf', 'cricket'],
	['ufc', 'wwe'],
	['twitch', 'netflix'],
	['twitter', 'facebook'],
	['spacex', 'tesla'],
	['burger king', 'mcdonald’s'],
	['sony', 'samsung'],
	['mercedes', 'bmw'],
	['harvard', 'mit'],
	['oxford', 'highschool'],
	['cia', 'fbi'],
	['hitler', 'stalin'],
	['tesla', 'porsche'],
	['iphone', 'samsung'],
	['playstation', 'xbox'],
	['windows', 'macos'],
	['youtube', 'tiktok'],
	['twitch', 'kick'],
	['spotify', 'apple music'],
	['reddit', 'discord'],
	['instagram', 'snapchat'],
	['chatgpt', 'gemini'],
	['clock', 'sundial'],
	['laptop', 'desktop'],
	['shark', 'dolphin'],
	['penguin', 'seagull'],
	['moon', 'planet'],
	['comet', 'asteroid'],
	['bridge', 'tunnel'],
	['bus', 'tram'],
	['train', 'monorail'],
	['boat', 'submarine'],
	['notebook', 'diary'],
	['spoon', 'fork'],
	['plate', 'bowl'],
	['fountain', 'waterfall'],
	['lake', 'pond'],
	['giraffe', 'zebra'],
	['elephant', 'rhino'],
	['alligator', 'crocodile'],
	['oyster', 'clam'],
	['gold', 'silver'],
	['platinum', 'gold'],
	['denim', 'corduroy'],
	['jacket', 'coat'],
	['scarf', 'tie'],
	['boots', 'sneakers'],
	['helmet', 'hat'],
	['necklace', 'bracelet'],
	['ring', 'earring'],
	['microphone', 'speaker'],
	['headphones', 'earbuds'],
	['television', 'radio'],
	['projector', 'screen'],
	['calculator', 'typewriter'],
	['flashlight', 'lantern'],
	['tent', 'cabin'],
	['compass', 'map'],
	['boarding pass', 'id card'],
	['ticket', 'invoice'],
	['passport', 'ticket'],
	['subway', 'taxi'],
	['sky', 'jet'],
	['motorcycle', 'scooter'],
	['surfboard', 'skateboard'],
	['baseball', 'football'],
	['volleyball', 'basketball'],
	['table tennis', 'badminton'],
	['bakery', 'butcher'],
	['puzzle', 'crossword'],
	['cards', 'dice'],
	['bowling', 'golf'],
	['marathon', 'sprint'],
	['fencing', 'archery'],
	['boxing', 'karate'],
	['hockey', 'soccer'],
	['concert', 'festival'],
	['novel', 'poem'],
	['dictionary', 'encyclopedia'],
	['pharmacist', 'doctor'],
	['engineer', 'architect'],
	['firefighter', 'policeman'],
	['germany', 'france'],
	['pilot', 'astronaut'],
	['judge', 'punishment'],
	['baker', 'chef'],
	['farmer', 'fisherman'],
	['blacksmith', 'carpenter'],
	['heaven', 'hell'],
	['sky', 'clouds'],
	['japan', 'china'],
	['germany', 'beer'],
	['movie', 'actor'],
	['screen', 'tv'],
	['france', 'eiffel tower'],
	['thor', 'lightning'],
	['obi wan', 'force'],
	['ufo', 'drones'],
	['god', 'heaven'],
	['tortilla', 'taco'],
	['baguette', 'ciabatta'],
	['hot dog', 'bratwurst'],
	['energy drink', 'soda'],
	['coconut milk', 'soy milk'],
	['picasso', 'van gogh'],
	['mozart', 'beethoven'],
	['messi', 'ronaldo'],
	['bayern munich', 'real madrid'],
	['ferrari', 'lamborghini'],
	['coca-cola', 'pepsi'],
	['london', 'paris'],
	['los angeles', 'new york'],
	['big ben', 'leaning tower of pisa'],
	['statue of liberty', 'eiffel tower'],
	['mouse', 'keyboard'],
	['tv', 'laptop'],
	['wardrobe', 'showcase'],
	['birch', 'shrub'],
	['radiator', 'hairdryer'],
	['lamp', 'candle'],
	['pillow', 'blanket'],
	['microphone', 'camera'],
	['oven', 'microwave'],
	['pan', 'pot'],
	['tablet', 'smartphone'],
	['stairs', 'elevator'],
	['techno', 'rap'],
	['rock', 'pop'],
	['table tennis', 'badminton'],
	['window', 'door'],
	['oven', 'heating'],
	['wristwatch', 'alarm clock'],
	['bed', 'sofa'],
	['book', 'newspaper'],
	['forest', 'park'],
	['cinema', 'bowling'],
	['netflix', 'cinema'],
	['swimming pool', 'beach'],
	['glass', 'cup'],
	['job', 'hobby'],
	['jesus', 'santa claus'],
	['bra', 'bikini'],
];
